#!/bin/sh
source $HOME/.cache/wal/colors.sh
sxhkd &
~/.xinitrc &

bspc monitor eDP1  -d 0 1 2 3 4

bspc config border_width           2.5
bspc config window_gap             5
bspc config right_padding          0
bspc config left padding           0

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config active_border_color    $color0
bspc config normal_border_color    $color0
bspc config focused_border_color   $color15
bspc config presel_feedback_color  $color15

bspc rule -a Firefox desktop=^1
bspc rule -a PomoDoneApp desktop=^5
bspc rule -a Pcmanfm desktop=^5
bspc rule -a "Google Play Music Desktop Player" desktop=^4
bspc rule -a Pavucontrol state=floating
bspc rule -a *:sun-awt-X11-XFramePeer state=floating
bspc rule -a octave-gui desktop=^5
bspc rule -a Code desktop=^3
bspc rule -a jetbrains-idea-ce desktop=^3

echo "/home/verb" > /tmp/wmdirectory &
adjust_gaps.sh &
