#!/bin/sh
sxhkd &
~/.xinitrc &

bspc monitor eDP1  -d 0 1 2 3 4

bspc config border_width           1.5
bspc config window_gap             5
bspc config right_padding          0
bspc config left padding           0

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config active_border_color   '#0D635A'
bspc config normal_border_color   '#1D1F21'
bspc config focused_border_color  '#003A34'
bspc config presel_feedback_color '#D8D8D8'

bspc rule -a Firefox desktop=^1
bspc rule -a PomoDoneApp desktop=^5
bspc rule -a Pcmanfm desktop=^5
bspc rule -a "Google Play Music Desktop Player" desktop=^5
bspc rule -a Pavucontrol state=floating
bspc rule -a *:sun-awt-X11-XFramePeer state=floating
bspc rule -a octave-gui desktop=^3
bspc rule -a Code desktop=^4
bspc rule -a jetbrains-idea-ce desktop=^4
